CREATE DATABASE rtk1open;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first VARCHAR(120) NOT NULL,
    last VARCHAR(120) NOT NULL,
    -- author VARCHAR(241) GENERATED ALWAYS AS (first || ' ' || last) STORED,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tales (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    text TEXT,
    poster VARCHAR(400),
    views INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT fk_story_author
        FOREIGN KEY (author_id)
        REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE INDEX idx_tales_author_id ON tales(author_id);


-- CREATE OR REPLACE VIEW story_with_author AS
--     SELECT
--         s.id,
--         s.author_id,
--         u.author,
--         s.title,
--         s.text,
--         s.poster,
--         s.views,
--         s.created_at,
--         s.updated_at
--     FROM story s
--     JOIN users u ON u.id = s.author_id;





